---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - autojump
  - git
  - tree
  - httpie
  - curl
  - wget
  - kubectl
  - kubernetes-helm
  - zsh
  - go
  - vim
  - hugo
  - saltstack
  - neovim
  - ag
  - ctags
  - terraform
  - minikube
  - node
  - tmux
  - terraform

# homebrew cask applications
cask_applications:
  - google-chrome
  - slack
  - mattermost
  - iterm2
  - caffeine
  - docker
  - vagrant
  - packer
  - emacs
  - alfred
  - virtualbox
  - spotify
  - bitwarden
  - dotnet-sdk
  - visual-studio-code
  - visual-studio
  - discord
  - postman
  - powershell


npm_modules:
  - protractor
  - grunt
  - karma
  - jest
